'use strict';


/**
 * @type {Record<string, KDLoadout>}
 */
let KDLoadouts = {
	"guard": {
		name: "guard",
		tags: ["elite"],
		singletag: ["human", "elf", "alchemist", "dragon", "witch", "apprentice", "mummy", "jailer"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.1,
		items: ["RedKey"],
	},
	"thief": {
		name: "guard",
		tags: ["human"],
		singletag: ["bandit", "bountyhunter"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.15,
		items: ["Pick", "Knife"],
	},
	"mistress": {
		name: "mistress",
		tags: ["miniboss"],
		singletag: ["human", "elf", "alchemist", "dragon", "witch", "apprentice", "mummy"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.65,
		items: ["RedKey"],
	},
	"scientist_I": {
		name: "scientist_I",
		tags: ["alchemist"],
		singletag: ["alchemist"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.65,
		items: ["SmokeBomb"],
	},
	"scientist_II": {
		name: "scientist_II",
		tags: ["alchemist"],
		singletag: ["alchemist"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.5,
		items: ["PotionFrigid", "PotionStamina"],
	},
	"scientist_III": {
		name: "scientist_III",
		tags: ["alchemist"],
		singletag: ["alchemist"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.35,
		items: ["PotionMana"],
	},
	"magus": {
		name: "magus",
		tags: [],
		singletag: ["dressmaker", "elf", "witch", "apprentice", "mummy", "fungal"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.01,
		multiplier: 10,
		items: ["BlueKey", "ScrollVerbal", "ScrollLegs", "ScrollArms"],
	},
	"magusElite": {
		name: "magusElite",
		tags: [],
		singletag: ["dressmaker", "elf", "witch", "apprentice", "mummy", "fungal"],
		singletag2: ["elite", "miniboss", "boss"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.6,
		multiplier: 10,
		items: ["BlueKey", "ScrollVerbal", "ScrollLegs", "ScrollArms"],
	},
	"scroll_arm": {
		name: "scroll_arm",
		tags: [],
		singletag: ["dressmaker", "elf", "witch", "apprentice", "mummy", "fungal"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.04,
		items: ["ScrollArms"],
	},
	"scroll_leg": {
		name: "scroll_arm",
		tags: [],
		singletag: ["dressmaker", "elf", "witch", "apprentice", "mummy", "fungal"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.04,
		items: ["ScrollLegs"],
	},
	"scroll_verbal": {
		name: "scroll_arm",
		tags: [],
		singletag: ["dressmaker", "elf", "witch", "apprentice", "mummy", "fungal"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.04,
		items: ["ScrollVerbal"],
	},
	"mage": {
		name: "mage",
		tags: [],
		singletag: ["witch", "apprentice", "fungal", "elf", "dressmaker"],
		forbidtags: [],
		chance: 0.08,
		items: ["PotionMana"],
	},
	"police": {
		name: "police",
		tags: ["police"],
		singletag: ["human", "bountyhunter"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.2,
		items: ["RedKey"],
	},
	"ninja": {
		name: "ninja",
		tags: [],
		singletag: ["ninja", "maid", "bountyhunter"],
		forbidtags: [],
		chance: 0.7,
		items: ["SmokeBomb"],
	},
	"bandit_I": {
		name: "bandit_I",
		tags: [],
		singletag: ["bandit"],
		forbidtags: [],
		chance: 0.3,
		items: ["Bomb"],
	},
	"bandit_II": {
		name: "bandit_II",
		tags: [],
		singletag: ["bandit"],
		forbidtags: [],
		chance: 0.7,
		items: ["Bola"],
	},
	"bandit_III": {
		name: "bandit_III",
		tags: ["bandit"],
		singletag: ["miniboss", "boss", "elite"],
		forbidtags: [],
		chance: 0.5,
		items: ["PotionStamina", "Bola", "Knife"],
	},
	"bandit_IV": {
		name: "bandit_IV",
		tags: ["bandit"],
		singletag: ["miniboss", "boss", "elite"],
		forbidtags: [],
		chance: 0.5,
		multiplier: 5,
		items: ["PotionWill", "Bomb", "Rope"],
	},
	"bandit_V": {
		name: "bandit_V",
		tags: ["bandit"],
		singletag: ["miniboss", "boss"],
		forbidtags: [],
		chance: 0.1,
		multiplier: 10,
		items: ["PotionStamina", "RedKey", "RedKey"],
	},
	"miner": {
		name: "miner",
		tags: ["miner"],
		singletag: ["miner"],
		forbidtags: [],
		chance: 1.0,
		items: ["Bomb", "Bomb", "Bomb"],
	},
	"trainer": {
		name: "trainer",
		tags: ["trainer"],
		singletag: ["trainer"],
		forbidtags: [],
		chance: 0.4,
		items: ["AncientPowerSource"],
	},
	"nevermere": {
		name: "nevermere",
		tags: ["nevermere"],
		singletag: ["trainer", "wolfgirl"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.15,
		items: ["AncientPowerSource", "RedKey"],
	},
	"agent": {
		name: "agent",
		tags: [],
		singletag: ["ninja", "maid", "bountyhunter"],
		forbidtags: [],
		chance: 0.1,
		items: ["SmokeBomb", "PotionInvisibility"],
	},
	"ninja_II": {
		name: "ninja_II",
		tags: [],
		singletag: ["ninja", "maid", "bountyhunter"],
		forbidtags: [],
		chance: 0.3,
		items: ["SmokeBomb", "Bola"],
	},
	"religious": {
		name: "religious",
		tags: ["religious"],
		singletag: ["mummy", "elf"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.01,
		items: ["ScrollPurity"],
	},
	"religiousElite": {
		name: "religiousElite",
		tags: ["religious", "elite"],
		singletag: ["mummy", "elf"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.2,
		multiplier: 4,
		items: ["ScrollPurity", "BlueKey"],
	},
	"religiousMiniboss": {
		name: "religiousMiniboss",
		tags: ["religious", "miniboss"],
		singletag: ["mummy", "elf"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.5,
		multiplier: 10,
		items: ["ScrollPurity", "BlueKey"],
	},
	"religiousBoss": {
		name: "religiousBoss",
		tags: ["religious", "boss"],
		singletag: ["mummy", "elf"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.8,
		multiplier: 10,
		items: ["ScrollPurity", "BlueKey"],
	},
	"keyholder": {
		name: "keyholder",
		tags: ["miniboss"],
		singletag: ["human", "elf", "alchemist", "dragon", "witch", "apprentice", "mummy", "jailer"],
		forbidtags: ["submissive", "gagged"],
		chance: 0.22,
		multiplier: 2,
		items: ["Keyring"],
	},
	"potMana_minor": {
		name: "potMana_minor",
		tags: ["jail"],
		singletag: [],
		forbidtags: [],
		chance: 0.05,
		items: ["PotionMana"],
	},
	"potStam_minor": {
		name: "potStam_minor",
		tags: ["jail"],
		singletag: [],
		forbidtags: [],
		chance: 0.05,
		items: ["PotionStamina"],
	},
	"potWill_minor": {
		name: "potWill_minor",
		tags: ["jail"],
		singletag: [],
		forbidtags: [],
		chance: 0.04,
		items: ["PotionWill"],
	},
	"potMana": {
		name: "potMana",
		tags: ["jail"],
		singletag: [],
		forbidtags: ["minor"],
		chance: 0.05,
		items: ["PotionMana"],
	},
	"potStam": {
		name: "potStam",
		tags: ["jail"],
		singletag: [],
		forbidtags: ["minor"],
		chance: 0.05,
		items: ["PotionStamina"],
	},
	"potWill": {
		name: "potWill",
		tags: ["jail"],
		singletag: [],
		forbidtags: ["minor"],
		chance: 0.04,
		items: ["PotionWill"],
	},
	"potFrigid": {
		name: "potFrigid",
		tags: ["jail"],
		singletag: [],
		forbidtags: ["minor"],
		chance: 0.08,
		items: ["PotionFrigid"],
	},
	"boss": {
		name: "boss",
		tags: ["boss"],
		singletag: ["human", "elf", "alchemist", "dragon", "witch", "apprentice", "mummy"],
		forbidtags: ["submissive", "gagged"],
		chance: 1.0,
		items: ["RedKey", "Keyring"],
	},
};

/** @type {Record<string, SpecialCondition>} */
let KDSpecialConditions = {
	"canRestrainWithExtra": {
		resetCD: false,
		criteria: (enemy, AIData) => {
			let rThresh = enemy.Enemy.RestraintFilter?.powerThresh || KDDefaultRestraintThresh;
			return KDGetRestraintsEligible(
				{tags: KDGetTags(enemy, true)}, MiniGameKinkyDungeonLevel,
				KinkyDungeonMapIndex[MiniGameKinkyDungeonCheckpoint],
				enemy.Enemy.bypass,
					enemy.Enemy.useLock ? enemy.Enemy.useLock : "",
					!(enemy.Enemy.ignoreStaminaForBinds || (true && enemy.Enemy.specialIgnoreStam)) && !AIData.attack.includes("Suicide"),
					false,
					!(KinkyDungeonStatsChoice.has("TightRestraints") || enemy.Enemy.tags.miniboss || enemy.Enemy.tags.boss),
					KDGetExtraTags(enemy, true),
					false,
					{
						maxPower: rThresh + 0.01,
						looseLimit: true,
						onlyUnlimited: true,
						ignore: enemy.items,
					}, enemy
			).length > 0;
		}
	}
};