input=../M1/Models/;
prefix=Models;
input=../M2/Models/;
prefix=Models;
input=../M3/Models/;
prefix=Models;
input=../M4/Models/;
prefix=Models;
input=../M5/Models/;
prefix=Models;
input=../Models/;
prefix=Models;
output=../TextureAtlas/;
atlas_size=2048;
atlas_prefix=models_mobile_;
input_scale=0.25;
alpha_cutoff=1;
padding=1;